/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void rollTest(){
        // Arrange
        Library sut = new Library();
        int[] testArray = {};
        // Act
        testArray = sut.roll(5);
        // Assert Dice roll returns number between 1 and 6
        // Assert that there are 5 things in my array
        assertTrue(testArray.length == 5);

    }

}
