/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashSet;

import static org.junit.jupiter.api.Assertions.*;
class LibraryTest {
    int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
    };
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void rollTest(){
        // Arrange
        Library sut = new Library();
        int[] testArray = {};
        // Act
        testArray = sut.roll(5);
        // Assert Dice roll returns number between 1 and 6
        // Assert that there are 5 things in my array
        assertTrue(testArray.length == 5);

    }

    @Test void testCalculateArrayAverage(){
        App sut = newApp();
        int[] testArray = {66, 64, 58, 65, 71, 57, 60};
        int result = sut.calculateAverage(testArray);
        assertNotNull(result);
        assertEquals((result*0) == 0));
    }
    @Test void analyzeWeatherData() {
        Library sut = new Library();

//        System.out.println(arr);
        assertTrue(sut.findNum(weeklyMonthTemperatures).equals("""
                High: 72
                Low: 51
                Never saw temperature: 63
                Never saw temperature: 67
                Never saw temperature: 68
                Never saw temperature: 69
                """ ));
    }


}
